# Generated by Django 4.2.4 on 2023-08-23 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('stripe_object', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to='user_manager.client')),
            ],
        ),
        migrations.CreateModel(
            name='StripePaymentMethod',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('stripe_object', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('row_limit', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_object', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='StripeProductPrice',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('base_price', models.IntegerField(default=0)),
                ('overage_price', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('monthly', 'MONTHLY'), ('annual', 'ANNUAL')], max_length=10)),
                ('billing_scheme', models.CharField(choices=[('per_unit', 'PER_UNIT'), ('tiered', 'TIERED')], max_length=10)),
                ('usage_type', models.CharField(choices=[('metered', 'METERED'), ('licensed', 'LICENSED')], max_length=10)),
                ('stripe_object', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stripe_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_product_price', to='user_billing.stripeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField()),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('trial_end_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('subscription_status', models.CharField(db_index=True, max_length=10)),
                ('stripe_object', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stripe_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subscription', to='user_billing.stripecustomer')),
                ('stripe_product_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subscription', to='user_billing.stripeproductprice')),
            ],
        ),
        migrations.CreateModel(
            name='StripeSubscriptionItem',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stripe_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subscription_item', to='user_billing.stripesubscription')),
            ],
        ),
        migrations.CreateModel(
            name='StripeInvoice',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('invoice_status', models.CharField(db_index=True, max_length=10)),
                ('invoice_pdf_url', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('stripe_object', models.JSONField()),
                ('stripe_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_invoice', to='user_billing.stripecustomer')),
            ],
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('customer.subscription.created', 'CUSTOMER_SUBSCRIPTION_CREATED'), ('customer.subscription.updated', 'CUSTOMER_SUBSCRIPTION_UPDATED'), ('customer.subscription.deleted', 'CUSTOMER_SUBSCRIPTION_DELETED'), ('customer.subscription.trial_will_end', 'CUSTOMER_SUBSCRIPTION_TRIAL_WILL_END'), ('payment_method.automatically_updated', 'PAYMENT_METHOD_AUTOMATICALLY_UPDATED'), ('payment_method.updated', 'PAYMENT_METHOD_UPDATED'), ('payment_method.attached', 'PAYMENT_METHOD_ATTACHED'), ('payment_method.detached', 'PAYMENT_METHOD_DETACHED')], max_length=255)),
                ('object_type', models.CharField(choices=[('subscription', 'SUBSCRIPTION'), ('customer', 'CUSTOMER')], max_length=50)),
                ('object_id', models.CharField(max_length=255)),
                ('stripe_object', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stripe_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_event', to='user_billing.stripecustomer')),
            ],
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='default_payment_method',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_billing.stripepaymentmethod'),
        ),
    ]
